---

- name: keyring
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C
  become: true
  tags: admin

- name: repository
  apt_repository:
    repo: "deb http://apt.insync.io/ubuntu {{ ansible_distribution_release }} non-free contrib"
    filename: insync
  become: true
  tags: admin

- name: package
  package:
    name: insync-nautilus
  become: true
  tags: admin
