---

- name: keyring
  apt_key:
    id: ACCAF35C
    keyserver: keyserver.ubuntu.com
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: insync
    repo: "deb http://apt.insync.io/ubuntu eoan non-free contrib"
  become: true
  tags: admin

- name: package
  package:
    name: insync
  become: true
  tags: admin
