---

- name: install package
  package: name='firefox'
  become: true
  tags: admin

- name: install locales
  package: name='{{item}}'
  with_items:
    - firefox-locale-en
    - firefox-locale-fr
  become: true
  tags: admin
