---

- name: package
  package:
    name: guake
  become: true
  tags: admin

- name: settings
  shell: "dconf load /apps/guake/ < {{ role_path }}/files/settings.ini"
  register: output
  changed_when: output.rc == 0
  tags: user
