---

- name: language
  package:
    name: guake
  become: true
  tags: admin

- name: configs
  shell: dconf load "{{ item|basename|replace('_', '/') }}" < "{{ item }}"
  with_fileglob:
    - "{{ role_path }}/files/*"
  when: true
  tags: user
