---

- name: install language
  package: name='guake'
  become: true
  tags: admin

- name: setup configuration
  shell: dconf load {{item|basename|replace("_", "/")}} < {{item}}
  with_fileglob:
    - '{{role_path}}/files/*'
  tags: user
