---

- hosts: localhost

  pre_tasks:

  - name: ~/bin/
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  - name: python-pip3
    package: name='python3-pip'
    tags: ['pre', 'package']

  roles:
    - {role: anki, tags: ['anki', 'application', 'education']}
    - {role: autogui, tags: ['autogui', 'desktop', 'automation']}
    - {role: chrome, tags: ['chrome', 'application', 'internet']}
    - {role: deja-dup, tags: ['deja-dup', 'application', 'security']}
    - {role: gnome, tags: ['gnome', 'desktop', 'environment']}
    - {role: guake, tags: ['guake', 'application', 'utility']}
    - {role: insync, tags: ['insync', 'extension', 'utility']}
    - {role: keepassx, tags: ['keepassx', 'application', 'security']}
    - {role: selenium, tags: ['selenium', 'automation', 'internet']}
    - {role: xvim, tags: ['xvim', 'application', 'editor']}
