---

- hosts: localhost

  tasks:

# LANG{{{
  - name: install french lang
    package: name='hunspell-fr'
    tags: ['sys', 'lang']
    become: true
# }}}
# CODEC{{{
  - name: install powerline fonts
    package: name='fonts-powerline'
    tags: ['sys', 'codec']
    become: true
# }}}
# APPLICATIONS{{{
  - name: install anki
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
        - anki
        - dvipng
    become: true

  - name: install deja-dup
    package: name='deja-dup'
    tags: ['sys', 'app']
    become: true

  - name: install krita
    package: name='krita'
    tags: ['sys', 'app']
    become: true

  - name: install keepassx
    package: name='keepassx'
    tags: ['sys', 'app']
    become: true

  - name: install owncloud
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - owncloud-client
      - dolphin-owncloud
    become: true

  - name: install tlp
    package: name='tlp'
    tags: ['sys', 'app']
    become: true

  - name: install unison
    package: name='unison-gtk'
    tags: ['sys', 'app']
    become: true

  - name: install vimx
    package: name='vim-gtk3'
    tags: ['sys', 'app']
    become: true

  - name: install vlc
    package: name='vlc'
    tags: ['sys', 'app']
    become: true

  - name: install xbacklight
    package: name='xbacklight'
    tags: ['sys', 'app']
    become: true

  - name: install xsel
    package: name='xsel'
    tags: ['sys', 'app']
    become: true

  - name: install yakuake
    package: name='yakuake'
    tags: ['sys', 'app']
    become: true
# }}}
