---

- hosts: localhost

  pre_tasks:

  - name: ensure ~/bin
    file:
      name: ~/bin
      state: directory
    tags: user

  - name: ensure pip3
    package:
      name: python3-pip
    become: true
    tags: admin

  roles:
    - {role: anki, tags: ['anki', 'education']}
    - {role: autostart, tags: ['autostart', 'automation']}
    - {role: chrome, tags: ['chrome', 'internet']}
    - {role: deja-dup, tags: ['deja-dup', 'security']}
    - {role: docker, tags: ['docker', 'develop']}
    # - {role: emacs, tags: ['emacs', 'develop']}
    - {role: gimp, tags: ['gimp', 'multimedia']}
    - {role: gnome, tags: ['gnome', 'environment']}
    - {role: gparted, tags: ['gparted', 'system']}
    - {role: guake, tags: ['guake', 'develop']}
    - {role: pyautogui, tags: ['pyautogui', 'automation']}
    # - {role: pycharm, tags: ['pycharm', 'develop']}
    - {role: splinter, tags: ['splinter', 'automation']}
    - {role: transmission, tags: ['transmission', 'internet']}
    - {role: vlc, tags: ['vlc', 'multimedia']}
    - {role: vscode, tags: ['vscode', 'develop']}
