---

- hosts: localhost

  pre_tasks:

  - name: pip
    package:
      name: python3-pip
    become: true
    tags: admin

  - name: ~/bin/
    file:
      name: ~/bin
      state: directory

  roles:
    # automation {{{
    - {role: autostart, tags: ['autostart', 'auto']}
    - {role: pyautogui, tags: ['pyautogui', 'auto']}
    - {role: splinter, tags: ['splinter', 'auto']}
    # }}}
    # background {{{
    - {role: deja-dup, tags: ['deja-dup', 'back']}
    - {role: insync, tags: ['insync', 'back']}
    # }}}
    # applications {{{
    - {role: anki, tags: ['anki', 'app']}
    - {role: chrome, tags: ['chrome', 'app']}
    - {role: gimp, tags: ['gimp', 'app']}
    - {role: gparted, tags: ['gparted', 'app']}
    - {role: guake, tags: ['guake', 'app']}
    - {role: keepassx, tags: ['keepassx', 'app']}
    - {role: liveusb, tags: ['liveusb', 'auto']}
    - {role: transmission, tags: ['transmission', 'app']}
    - {role: vlc, tags: ['vlc', 'app']}
    # }}}
    # environments {{{
    - {role: gnome, tags: ['gnome', 'env']}
    # }}}
