---

- hosts: localhost

  tasks:

# REPO {{{

# }}}
 
# LANG {{{

  - name: install french lang
    package: name='hunspell-fr'
    tags: ['sys', 'prog', 'pkg', 'plug']
    become: true

# CODEC {{{

  - name: install powerline fonts
    package: name='fonts-powerline'
    tags: ['sys', 'prog', 'pkg', 'plug']
    become: true

# }}}

# GNOME {{{

  - name: install gnome tweak tool
    package: name='gnome-tweak-tool'
    tags: ['sys', 'gnome', 'pkg', 'exec']
    become: true

  - name: install gnome chrome shell
    package: name='chrome-gnome-shell'
    tags: ['sys', 'gnome', 'pkg', 'plug']
    become: true

  - name: install gnome extensions
    package: name='chrome-gnome-shell'
    tags: ['sys', 'gnome', 'pkg', 'plug']
    with_items:
        # pomodoro
        # do not disturb
        # drop down terminal
        - gnome-shell-extension-pixelsaver
        - gnome-shell-extension-impactience
        - gnome-shell-extension-no-annoyance
        - gnome-shell-extension-top-icons-plus
    become: true

# }}}

# PROGRAMS {{{

  - name: install anki
    package: name='{{item}}'
    tags: ['sys', 'prog', 'pkg', 'exec']
    with_items:
        - anki
        - dvipng
    become: true

  - name: install deja-dup
    package: name='deja-dup'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install firefox
    package: name='firefox'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install gimp
    package: name='gimp'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install keepassx
    package: name='keepassx'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  # - name: install nextcloud
  #   package: name='nautilus-owncloud'
  #   tags: ['sys', 'prog', 'pkg', 'exec']
  #   become: true

  - name: install tlp
    package: name='tlp'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install unison
    package: name='unison-gtk'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install vlc
    package: name='vlc'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install xbacklight
    package: name='xbacklight'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: install xsel
    package: name='xsel'
    tags: ['sys', 'prog', 'pkg', 'exec']
    become: true

  - name: download zotero
    unarchive: src='https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.44' dest='/opt/' remote_src=yes
    tags: ['sys', 'prog', 'zip', 'exec']
    become: true

  - name: link zotero exec
    file: src='/opt/Zotero_linux-x86_64/zotero' dest='/usr/local/bin/zotero' state='link' force=yes
    tags: ['sys', 'prog', 'file', 'link']
    become: true

  - name: link zotero desktop
    file: src='/opt/Zotero_linux-x86_64/zotero.desktop' dest='/usr/share/applications/zotero.desktop' state='link' force=yes
    tags: ['sys', 'prog', 'file', 'link']
    become: true

# }}}
