---

- hosts: localhost

  tasks:

# INIT {{{
  - name: install pip3
    package: name='python3-pip'
    tags: ['sys', 'init']

  - name: create ~/bin
    file: name='~/bin' state='directory'
    tags: ['usr', 'init']
# }}}
# LANG {{{
  - name: install french lang
    package: name='hunspell-fr'
    tags: ['sys', 'lang']
    become: true
# }}}
# GNOME{{{
  - name: install gnome tweak
    package: name='gnome-tweak-tool'
    tags: ['sys', 'gnome']
    become: true

  - name: install gnome chrome
    package: name='chrome-gnome-shell'
    tags: ['sys', 'gnome']
    become: true

  - name: install gnome extensions
    package: name='chrome-gnome-shell'
    tags: ['sys', 'gnome']
    with_items:
      - gnome-shell-extension-weather
      - gnome-shell-extension-pixelsaver
      - gnome-shell-extension-impactience
      - gnome-shell-extension-no-annoyance
      - gnome-shell-extension-top-icons-plus
      - gnome-shell-extension-system-monitor
      - gnome-shell-extension-tilix-dropdown
    become: true
# }}}
# CODEC {{{
  - name: install emoji fonts
    package: name='fonts-emojione'
    tags: ['sys', 'codec']
    become: true

  - name: install powerline fonts
    package: name='fonts-powerline'
    tags: ['sys', 'codec']
    become: true
# }}}
# AUTOMATION {{{
  - name: install autogui
    pip: name='pyautogui' executable='pip3' extra_args='--user'
    tags: ['usr', 'automation']

  - name: install autogui deps
    package: name='{{item}}'
    with_items:
      - scrot
      - python3-tk
      - python3-dev
      - python3-xlib
    tags: ['sys', 'automation']
    become: true

  - name: deploy autogui scripts
    file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
    tags: ['usr', 'automation']
    with_fileglob:
      - 'autogui/*'

  - name: install splinter
    pip: name='splinter' executable='pip3' extra_args='--user'
    tags: ['usr', 'automation']

  - name: install splinter deps
    pip: name='{{item}}' executable='pip3' extra_args='--user'
    with_items:
      - selenium
    tags: ['usr', 'automation']

  - name: install splinter drivers
    unarchive: src='https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz' dest='~/bin/' remote_src=yes
    tags: ['usr', 'automation']

  - name: deploy splinter scripts
    file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
    tags: ['usr', 'automation']
    with_fileglob:
      - 'splinter/*'
# }}}
# EXTENSIONS {{{
  - name: install vimx
    package: name='vim-gtk3'
    tags: ['sys', 'ext']
    become: true

  - name: install xsel
    package: name='xsel'
    tags: ['sys', 'ext']
    become: true

  - name: install xbacklight
    package: name='xbacklight'
    tags: ['sys', 'ext']
    become: true
# }}}
# APPLICATIONS {{{
  - name: install anki
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - anki
      - dvipng
    become: true

  - name: install deja-dup
    package: name='deja-dup'
    tags: ['sys', 'app']
    become: true

  - name: install firefox
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - firefox
      - firefox-locale-en
      - firefox-locale-fr
    become: true

  - name: install empathy
    package: name='empathy'
    tags: ['sys', 'app']
    become: true

  - name: install evolution
    package: name='evolution'
    tags: ['sys', 'app']
    become: true

  - name: install gimp
    package: name='gimp'
    tags: ['sys', 'app']
    become: true

  - name: install keepassx
    package: name='keepassx'
    tags: ['sys', 'app']
    become: true

  - name: install owncloud
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - libgnome-keyring0
      - nautilus-owncloud
    become: true
# }}}
