---

- hosts: localhost

  roles:
    - {role: anki, tags: ['anki', 'app']}
    - {role: autostart, tags: ['autostart', 'desktop']}
    - {role: chrome, tags: ['chrome', 'app']}
    - {role: deja-dup, tags: ['deja-dup', 'app']}
    - {role: gimp, tags: ['gimp', 'app']}
    - {role: gnome, tags: ['gnome', 'desktop']}
    - {role: gparted, tags: ['gparted', 'app']}
    # - {role: guake, tags: ['guake', 'desktop']}
    - {role: transmission, tags: ['transmission', 'app']}
    - {role: vlc, tags: ['vlc', 'app']}
    - {role: vscode, tags: ['vscode', 'app']}
