---

- hosts: localhost

  pre_tasks:

  - name: install python pip3
    package: name='python3-pip'
    tags: ['pre', 'package']

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: anacron, tags: ['anacron', 'automation', 'scheduler']}
    - {role: anki, tags: ['anki', 'application', 'education']}
    - {role: autogui, tags: ['autogui', 'automation', 'keyboard']}
    - {role: deja-dup, tags: ['deja-dup', 'application', 'backup']}
    - {role: empathy, tags: ['empathy', 'application', 'communication']}
    - {role: evolution, tags: ['evolution', 'application', 'communication']}
    - {role: firefox, tags: ['firefox', 'application', 'internet']}
    - {role: gimp, tags: ['gimp', 'application', 'graphism']}
    - {role: gnome, tags: ['gnome', 'desktop', 'environment']}
    - {role: keepassx, tags: ['keepassx', 'application', 'security']}
    - {role: owncloud, tags: ['owncloud', 'application', 'internet']}
    - {role: powerfonts, tags: ['powerfonts', 'extension', 'fonts']}
    - {role: splinter, tags: ['splinter', 'automation', 'browser']}
    - {role: vimx, tags: ['vimx', 'extension', 'editor']}
    - {role: xbacklight, tags: ['xbacklight', 'extension', 'light']}
    - {role: xsel, tags: ['xsel', 'extension', 'editor']}
