---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin' state='directory'

  roles:
    - {role: anki, tags: ['anki']}
    - {role: autogui, tags: ['autogui']}
    - {role: autostart, tags: ['autostart']}
    - {role: chrome, tags: ['chrome']}
    - {role: deja-dup, tags: ['deja-dup']}
    - {role: french, tags: ['french']}
    - {role: gimp, tags: ['gimp']}
    - {role: gnome, tags: ['gnome']}
    - {role: guake, tags: ['guake']}
    - {role: insync, tags: ['insync']}
    - {role: keepassx, tags: ['keepassx']}
    - {role: selenium, tags: ['selenium']}
