---

- hosts: localhost

  pre_tasks:

  - name: prepare npm
    package: name='npm'
    tags: ['pre', 'package']

  - name: prepare pip
    package: name='python3-pip'
    tags: ['pre', 'package']

  - name: prepare bin
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: anki, tags: ['anki', 'education']}
    - {role: autogui, tags: ['autogui', 'automation']}
    - {role: chrome, tags: ['chrome', 'internet']}
    - {role: deja-dup, tags: ['deja-dup', 'security']}
    - {role: gimp, tags: ['gimp', 'graphic']}
    - {role: gnome, tags: ['gnome', 'desktop']}
    - {role: guake, tags: ['guake', 'utility']}
    - {role: insync, tags: ['insync', 'utility']}
    - {role: keepassx, tags: ['keepassx', 'security']}
    - {role: selenium, tags: ['selenium', 'automation']}
