---

- hosts: localhost

  pre_tasks:

  - name: install python pip3
    package: name='python3-pip'
    tags: ['pre', 'package']

  - name: create bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: anki, tags: ['anki', 'application', 'education']}
    - {role: deja-dup, tags: ['deja-dup', 'application', 'backup']}
    - {role: firefox, tags: ['firefox', 'application', 'browser']}
    - {role: gnome, tags: ['gnome', 'desktop', 'environment']}
    - {role: guake, tags: ['guake', 'application', 'utility']}
    - {role: keepassx, tags: ['keepassx', 'application', 'security']}
    - {role: owncloud, tags: ['owncloud', 'application', 'utility']}
    - {role: powerfonts, tags: ['powerfonts', 'extension', 'fonts']}
    - {role: xsel, tags: ['xsel', 'extension', 'clipboard']}
    - {role: xvim, tags: ['xvim', 'application', 'editor']}
