---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin' state='directory'

  roles:
    # automation {{{
    - {role: autostart, tags: ['autostart', 'auto']}
    - {role: pyautogui, tags: ['pyautogui', 'auto']}
    - {role: splinter, tags: ['splinter', 'auto']}
    # }}}
    # background {{{
    - {role: deja-dup, tags: ['deja-dup', 'back']}
    - {role: insync, tags: ['insync', 'back']}
    # }}}
    # applications {{{
    - {role: anki, tags: ['anki', 'apps']}
    - {role: chrome, tags: ['chrome', 'apps']}
    - {role: evolution, tags: ['evolution', 'apps']}
    - {role: gimp, tags: ['gimp', 'apps']}
    - {role: gparted, tags: ['gparted', 'apps']}
    - {role: guake, tags: ['guake', 'apps']}
    - {role: keepassx, tags: ['keepassx', 'apps']}
    - {role: liveusb, tags: ['liveusb', 'auto']}
    - {role: transmission, tags: ['transmission', 'apps']}
    # }}}
    # environments {{{
    - {role: gnome, tags: ['gnome', 'envs']}
    # }}}
