---

- hosts: localhost

  tasks:

# INIT {{{
  - name: install pip
    package: name='python3-pip'
    tags: ['sys', 'init']

  - name: create ~/bin
    file: name='~/bin' state='directory'
    tags: ['usr', 'init']
# }}}
# LANG {{{
  - name: install french lang
    package: name='hunspell-fr'
    tags: ['sys', 'lang']
    become: true
# }}}
# KDE {{{
# }}}
# CODEC {{{
  - name: install powerline fonts
    package: name='fonts-powerline'
    tags: ['sys', 'codec']
    become: true
# }}}
# AUTOMATION {{{
  - name: install autogui
    pip: name='pyautogui' executable='pip3' extra_args='--user'
    tags: ['usr', 'automation']

  - name: install autogui deps
    package: name='{{item}}'
    with_items:
      - scrot
      - python3-tk
      - python3-dev
      - python3-xlib
    tags: ['sys', 'automation']
    become: true

  - name: deploy autogui scripts
    file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
    tags: ['usr', 'automation']
    with_fileglob:
      - 'autogui/*'

  - name: install splinter
    pip: name='splinter' executable='pip3' extra_args='--user'
    tags: ['usr', 'automation']

  - name: install splinter deps
    pip: name='{{item}}' executable='pip3' extra_args='--user'
    with_items:
      - selenium
    tags: ['usr', 'automation']

  - name: install splinter drivers
    unarchive: src='https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz' dest='~/bin/' remote_src=yes
    tags: ['usr', 'automation']

  - name: deploy splinter scripts
    file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
    tags: ['usr', 'automation']
    with_fileglob:
      - 'splinter/*'
# }}}
# APPLICATIONS {{{
  - name: install anki
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
        - anki
        - dvipng
    become: true

  - name: install firefox
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - firefox
      - firefox-locale-en
      - firefox-locale-fr
    become: true

  - name: install krita
    package: name='krita'
    tags: ['sys', 'app']
    become: true

  - name: install kazam
    package: name='kazam'
    tags: ['sys', 'app']
    become: true

  - name: install keepassx
    package: name='keepassx'
    tags: ['sys', 'app']
    become: true

  - name: install kup
    package: name='kup-backup'
    tags: ['sys', 'app']
    become: true

  - name: install kwalletcli
    package: name='kwalletcli'
    tags: ['sys', 'app']
    become: true

  - name: install owncloud
    package: name='{{item}}'
    tags: ['sys', 'app']
    with_items:
      - owncloud-client
      - dolphin-owncloud
    become: true

  - name: install tlp
    package: name='tlp'
    tags: ['sys', 'app']
    become: true

  - name: install unison
    package: name='unison-gtk'
    tags: ['sys', 'app']
    become: true

  - name: install vimx
    package: name='vim-gtk3'
    tags: ['sys', 'app']
    become: true

  - name: install vlc
    package: name='vlc'
    tags: ['sys', 'app']
    become: true

  - name: install xbacklight
    package: name='xbacklight'
    tags: ['sys', 'app']
    become: true

  - name: install xsel
    package: name='xsel'
    tags: ['sys', 'app']
    become: true

  - name: install yakuake
    package: name='yakuake'
    tags: ['sys', 'app']
    become: true
# }}}
