---

- hosts: localhost

  roles:
    - {role: anki, tags: ['anki', 'education']}
    - {role: autostart, tags: ['autostart', 'automation']}
    - {role: chrome, tags: ['chrome', 'internet']}
    - {role: deja-dup, tags: ['deja-dup', 'security']}
    - {role: gimp, tags: ['gimp', 'multimedia']}
    - {role: gnome, tags: ['gnome', 'desktop']}
    - {role: gparted, tags: ['gparted', 'system']}
    - {role: guake, tags: ['guake', 'desktop']}
    - {role: insync, tags: ['insync', 'internet']}
    - {role: transmission, tags: ['transmission', 'internet']}
    - {role: vlc, tags: ['vlc', 'multimedia']}
    - {role: vscode, tags: ['vscode', 'develop']}
