---

- name: add repository
  apt_repository: repo='ppa:smathot/cogscinl' filename='zotero'
  become: true
  tags: admin

- name: install package
  package: name='zotero-standalone'
  become: true
  tags: admin
