---

- name: directory
  file:
    state: directory
    name: ~/.config/autostart
    mode: 0750
  tags: user

- name: scripts
  file:
    dest: "~/.config/autostart/{{ item|basename }}"
    src: "{{ item }}"
    state: link
    force: yes
  with_fileglob:
    - "{{ role_path }}/files/*"
  tags: user
