---

- name: directory
  file:
    state: directory
    name: ~/.config/autostart
  tags: user

- name: scripts
  file:
    force: yes
    state: link
    src: "{{ item }}"
    dest: "~/.config/autostart/{{ item|basename }}"
  with_fileglob:
    - "{{ role_path }}/files/*"
  tags: user
