---

- name: identify repository
  apt_key: url='https://packages.microsoft.com/keys/microsoft.asc'
  become: true
  tags: admin

- name: install repository
  apt_repository: filename='vscode' repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
  become: true
  tags: admin

- name: install package
  package: name='code'
  become: true
  tags: admin

- name: create directory
  file: name='~/.config/Code/User' state='directory'
  tags: user

- name: deploy snippets
  file: src='{{role_path}}/files/snippets' dest='~/.config/Code/User/snippets' state=link force=yes
  tags: user

- name: deploy settings
  file: src='{{role_path}}/files/settings.json' dest='~/.config/Code/User/settings.json' state=link force=yes
  tags: user
