---

- name: keyring
  apt_key: url='https://packages.microsoft.com/keys/microsoft.asc'
  become: true
  tags: admin

- name: repository
  apt_repository: filename='vscode' repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
  become: true
  tags: admin

- name: package
  package: name='code'
  become: true
  tags: admin

- name: directory
  file: name='~/.config/Code/User' state='directory'
  tags: user

- name: config
  file: src='{{role_path}}/files/settings.json' dest='~/.config/Code/User/settings.json' state=link force=yes
  tags: user

- name: snippets
  file: src='{{role_path}}/files/snippets' dest='~/.config/Code/User/snippets' state=link force=yes
  tags: user
