---

- name: install language
  package: name='hunspell-fr'
  become: true
  tags: admin

- name: setup keybindings
  shell: dconf load {{item|basename|replace("_", "/")}} < {{item}}
  with_fileglob:
    - '{{role_path}}/files/*'
  tags: user

- name: install tweak tool
  package: name='gnome-tweak-tool'
  become: true
  tags: admin

- name: install chrome shell
  package: name='chrome-gnome-shell'
  become: true
  tags: admin
