---

- name: install language
  package: name='{{item}}'
  become: true
  with_items:
    - hunspell-fr

- name: install tweak tool
  package: name='gnome-tweak-tool'
  become: true

- name: install chrome shell
  package: name='chrome-gnome-shell'
  become: true
