---

- name: languages
  package: name='{{item}}'
  with_items:
      - hunspell-fr
      - hunspell-en-us
  become: true
  tags: admin

- name: tweak
  package: name='gnome-tweak-tool'
  become: true
  tags: admin

- name: clip
  package: name='xclip'
  become: true
  tags: admin

- name: configs
  shell: dconf load {{item|basename|replace("_", "/")}} < {{item}}
  with_fileglob:
    - '{{role_path}}/files/confs/*'
  tags: user

- name: desktops
  file: src='{{item}}' dest='~/.config/autostart/{{item | basename}}' state='link' force=yes
  with_fileglob:
    - '{{role_path}}/files/desktops/*'
  tags: user
