---

- name: install language
  package: name='hunspell-fr'
  become: true
  tags: admin

- name: install tweak tool
  package: name='gnome-tweak-tool'
  become: true
  tags: admin

- name: install chrome shell
  package: name='chrome-gnome-shell'
  become: true
  tags: admin
