---

- name: fonts
  package:
    name:
      - fonts-firacode
  become: true
  tags: admin

- name: langs
  package:
    name:
      - hunspell-fr
      - hunspell-en-us
      - language-pack-en
      - language-pack-fr
      - language-pack-gnome-en
      - language-pack-gnome-fr
  become: true
  tags: admin

- name: tweaks
  package:
    name: gnome-tweaks
  become: true
  tags: admin

- name: configs
  shell: "dconf load / < {{ role_path }}/files/settings.ini"
  tags: user
