---

- name: language
  package: name='hunspell-fr'
  become: true
  tags: admin

- name: tweak
  package: name='gnome-tweak-tool'
  become: true
  tags: admin

- name: bindings
  shell: dconf load {{item|basename|replace("_", "/")}} < {{item}}
  with_fileglob:
    - '{{role_path}}/files/*'
  tags: user
