---

- name: dependency
  pip:
    name: selenium
    executable: pip3
    extra_args: --user
  tags: user

- name: package
  pip:
    name: splinter
    executable: pip3
    extra_args: --user
  tags: user

- name: driver
  unarchive:
    dest: ~/Scripts/
    remote_src: yes
    src: 'https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip'
  tags: user
