---

- name: install dependencies
  pip: name='{{item}}' executable='pip3' extra_args='--user'
  with_items:
    - selenium

- name: install package
  pip: name='splinter' executable='pip3' extra_args='--user'

- name: install drivers
  unarchive: src='https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz' dest='~/bin/' remote_src=yes

- name: deploy scripts
  file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
  with_fileglob:
    - 'files/*'
