---

- name: repository
  copy: src='google-chrome.repo' dest='/etc/yum.repos.d/' owner='root' group='root' mode='0644'
  become: true
  tags: admin

- name: package
  package: name='google-chrome-stable'
  become: true
  tags: admin
