---

- name: keyring
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: google-chrome
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
  become: true
  tags: admin

- name: package
  package:
    name: google-chrome-stable
  become: true
  tags: admin
