---

- name: dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - scrot
      - python3-tk
      - python3-dev
      - python3-xlib
  become: true
  tags: admin

- name: package
  pip:
    name: pyautogui
    executable: pip3
    extra_args: --user
  tags: user
