---

- name: install dependencies
  package: name='{{item}}'
  with_items:
    - scrot
    - python3-tk
    - python3-dev
    - python3-xlib
  become: true

- name: install package
  pip: name='pyautogui' executable='pip3' extra_args='--user'

- name: deploy scripts
  file: src='{{item}}' dest='~/bin/{{item | basename}}' state='link' force=yes
  with_fileglob:
    - 'files/*'
